name: Build/Test Branch
on:
  workflow_dispatch:
    inputs:
      driver_revision:
        description: "Driver revision to use, if not the latest"
        required: false
      clobber:
        description: "Build the browser from scratch"
        type: boolean
        required: false
      slot:
        description: "Checked out repository slot to use"
        required: false
      test_runs:
        description: "Number of times to run tests"
        required: false
        default: "1"

jobs:
  build-test:
    name: Trigger build/test run on current branch
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@e870a1112fcc1faeeeeea3c1b0ce544e5ad01844
        with:
          authkey: ${{ secrets.TAILSCALE_API_KEY }}
          version: "1.28.0"
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-test-branch
        env:
          BUILD_TEST_AUTHORIZATION: ${{ secrets.BUILD_TEST_AUTHORIZATION }}
          BUILD_TEST_HOSTNAME: a49855c191a944333918aea7ad31bc76-6a8a830d89921d8a.elb.us-east-2.amazonaws.com
          BUILD_TEST_PORT: ${{ secrets.BUILD_TEST_PORT }}
          BUILD_TEST_INSECURE: ${{ secrets.BUILD_TEST_INSECURE }}
          INPUT_DRIVER_REVISION: ${{ github.event.inputs.driver_revision }}
          INPUT_CLOBBER: ${{ github.event.inputs.clobber }}
          INPUT_SLOT: ${{ github.event.inputs.slot }}
          INPUT_TEST_RUNS: ${{ github.event.inputs.test_runs }}
