name: Merge from upstream

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  merge:
    name: Merge from upstream branch
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@effa99fe9dc68518c77d0e7c00879f6599714d39
        with:
          authkey: ${{ secrets.TAILSCALE_API_KEY }}
          version: "1.26.0"
      - uses: actions/checkout@v2
        with:
          ref: webreplay-release
      - uses: ./.github/actions/merge-upstream
        env:
          BUILD_TEST_AUTHORIZATION: ${{ secrets.BUILD_TEST_AUTHORIZATION }}
          BUILD_TEST_HOSTNAME: build-server.replay.prod
          BUILD_TEST_PORT: ${{ secrets.BUILD_TEST_PORT }}
          BUILD_TEST_INSECURE: ${{ secrets.BUILD_TEST_INSECURE }}
